# Generated by Django 5.2 on 2025-05-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionresult',
            name='category',
        ),
        migrations.RemoveField(
            model_name='predictionresult',
            name='created_at',
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='event',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='gender',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='occupation',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='predicted_category',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='unit',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='recommended_products',
            field=models.TextField(default='No products recommended'),
        ),
    ]
