# Generated by Django 5.2 on 2025-05-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_remove_predictionresult_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='recommended_products',
            field=models.JSONField(default=list),
        ),
    ]
