# Generated by Django 5.2 on 2025-05-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_alter_predictionresult_recommended_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='event',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='gender',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='occupation',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='predicted_category',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='unit',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
