# Generated by Django 5.2 on 2025-06-03 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_alter_predictionresult_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='event',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='gender',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='occupation',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='predicted_category',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='unit',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.productcategory')),
            ],
        ),
    ]
