# Generated by Django 5.2.2 on 2025-06-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_remove_predictionresult_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='unit',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
