# Generated by Django 5.2 on 2025-06-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0012_remove_predictionresult_unit_productcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='slug',
        ),
    ]
