# Generated by Django 5.2.2 on 2025-06-20 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0014_productcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='slug',
        ),
    ]
