# Generated by Django 5.2.2 on 2025-06-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0015_remove_productcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
