# Generated by Django 5.2.2 on 2025-06-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_predictionresult_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionresult',
            name='unit',
        ),
    ]
