# Generated by Django 5.2.2 on 2025-06-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0010_remove_predictionresult_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='unit',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
