# Generated by Django 5.2.2 on 2025-06-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0011_predictionresult_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionresult',
            name='unit',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
