# Generated by Django 5.2 on 2025-06-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0013_remove_productcategory_slug'),
    ]

    operations = [
        migrations.AddField(
        model_name='productcategory',
        name='slug',
        field=models.SlugField(unique=True, blank=True, default='temp'),
        preserve_default=False,
    )

    ]
